default_gateway: local
gateways:
  local:
    connection:
      database: demosqlmesh2
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      password: postgres
model_defaults:
  dialect: postgres
  start: '2024-01-01'
