name: "olist_ecommerce"

version: 1.0.0
profile: postgres_env

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

models:
  olist_ecommerce:
    staging:
      +materialized: view
    compute:
      +materialized: table
    published:
      +materialized: table